const projects = [
    {
        id: 0,
        categoryId: [1, 2, 3],
        name: "Gestus",
        description: "Gestus é um recurso educativo digital composto por minigames que ensinam termos em LIBRAS para crianças de 7 a 10 anos. O  jogo dispõe de uma narrativa onde o personagem principal, Jonas, ajuda a ambientar a história dentro de uma cidade, onde cada local — casa, sorveteria, supermercado, fliperama e escola — comporta um aprendizado. \nEm Gestus se aborda o básico de LIBRAS por meio de módulos. Essa separação em módulos proporciona uma maior flexibilidade no momento da aula, pois permite que o professor escolha a quantidade de módulos por aula e aumenta as possibilidades de uso da aplicação. \nO  jogo Gestus tem por finalidade aproximar o contato de crianças, entre 7 a 10 anos de idade, com o ensino de LIBRAS, de modo a tornar natural esse processo de aprendizado através de jogos, bem como auxiliar no processo de adaptação de crianças ouvintes com crianças surdas em um mesmo espaço escolar.",
        descriptionCard: "Gestus é um recurso educativo digital composto por minigames que ensinam termos em LIBRAS para crianças de 7 a 10 anos.",
        imgUrl: "../images/projects/0.png",
        demoUrl: "https://www.youtube.com/embed/PcrJng0BVeo",
        acess: "https://gestusjogo.github.io/",
        heldIn: "Projeto Integrado I - 3º semestre",
        partcipants: "Espedito Roza, José Monteiro, Rafaelly Freitas, Sarah Isabelle, Vinícius Dellvale",
    },
    {
        id: 1,
        categoryId: [1, 3],
        name: "Ariel",
        description: "O Projeto Ariel é uma plataforma que auxilia homens trans em todas as etapas da hormonoterapia. Ele oferece recursos personalizados para o controle das doses de testosterona, o acompanhamento de parâmetros como secreção vaginal, alterações de humor e mudanças corporais. Os usuários também podem registrar as mudanças físicas por meio de fotos, acessar artigos sobre saúde, humor e sociedade, adicionar eventos ao calendário para consultas e exames, além de acompanhar os níveis de testosterona para uma transição através de hormonoterapia saudável e bem-sucedida. O objetivo principal do Projeto Ariel é fornecer um suporte abrangente e personalizado aos homens trans durante todo o processo de hormonoterapia, auxiliando-os a ter uma transição segura, saudável e satisfatória. O projeto busca empoderar os usuários, fornecendo ferramentas e recursos que os capacitam a tomar decisões informadas, monitorar seu progresso, gerenciar sua saúde física e emocional, e se manterem atualizados com informações relevantes e de qualidade.\nAo oferecer uma plataforma que integra diversos recursos, desde o acompanhamento das doses de testosterona até o registro de mudanças físicas, leitura de artigos, calendário personalizado e monitoramento dos níveis hormonais, o Ariel visa simplificar e centralizar todas as informações e tarefas relacionadas à transição hormonal. Dessa forma, o projeto busca facilitar o processo para os homens trans, fornecendo uma ferramenta prática, confiável e acessível, que os acompanha em cada etapa de sua jornada de transição.",
        descriptionCard: "O Projeto Ariel é uma plataforma que auxilia homens trans em todas as etapas da hormonoterapia.",
        imgUrl: "../images/projects/1.png",
        demoUrl: "https://www.youtube.com/embed/t-hK0KsicPQ",
        acess: "https://repositorio.ufc.br/handle/riufc/68044",
        heldIn: "Projeto Integrado II - 6º semestre",
        partcipants: "Versão menor do projeto: Espedito Roza, Matheus Felix, Rafinha Freitas, Sarah Isabelle:",
    },
    {
        id: 2,
        categoryId: [1, 2, 3],
        name: "The Gatsby’s Party",
        description: `O Projeto The Gatsby's Party é um jogo digital para desktop criado com o objetivo de testar os alunos em relação ao livro "The Great Gatsby" de Scott Fitzgerald. \nO jogo oferece uma abordagem interativa e envolvente para incentivar o aprendizado do livro, combinando elementos de quiz, escape room e exploração de objetos. O jogo começa com um quiz sobre o personagem escolhido pelo usuário. Para avançar no jogo, o jogador precisa acertar pelo menos 3 das 5 perguntas apresentadas. Isso garante que o jogador tenha um conhecimento básico sobre o livro e os personagens principais. Uma vez que o usuário tenha passado no quiz inicial, ele entra na festa de Gatsby. O jogo se desenrola em estilo escape room, onde o jogador precisa encontrar objetos, resolver enigmas e desafios para progredir e alcançar o objetivo final. Durante essa jornada, o jogador é exposto a informações sobre o livro, como curiosidades, trechos destacados e análises literárias. Essas informações complementares ajudam no aprendizado do livro de forma divertida e imersiva. \nO Projeto The Gatsby's Party busca não apenas testar os conhecimentos dos alunos, mas também promover o envolvimento e o interesse pela obra literária. Ao combinar elementos de jogo com aprendizado, o projeto oferece uma experiência interativa que estimula a curiosidade e a exploração do universo de "The Great Gatsby", tornando o processo de estudo mais envolvente e prazeroso.`,
        descriptionCard: `O Projeto The Gatsby's Party é um jogo digital para desktop criado com o objetivo de testar os alunos em relação ao livro "The Great Gatsby" de Scott Fitzgerald.`,
        imgUrl: "../images/projects/2.png",
        demoUrl: "../images/projects/demo/2.png",
        acess: "https://thegatsbyparty.github.io/index.html ",
        heldIn: "Avaliação Interdisciplinar - 2º semestre",
        partcipants: "Arlindo Júnior, Davi Calisto, Espedito Roza, Sarah Isabelle, Vinícius Dellvale",
    },
    {
        id: 3,
        categoryId: [0],
        name: "Imaginarium - Uma Leitura Brincante",
        description: "Amanda é uma criança comum. Ela tem amigos, diverte-se com eles, mas em certos momentos se encontra solitária e fica triste. Por muito tempo, Amanda acreditou que não havia graça em brincar sozinha. Imagine a surpresa dela ao descobrir a sua brincadeira preferida na vida, incomum e maravilhosa…",
        descriptionCard: "Amanda é uma criança comum. Ela tem amigos, diverte-se com eles, mas em certos momentos se encontra solitária e fica triste.",
        imgUrl: "../images/projects/3.jpg",
        demoUrl: "https://www.youtube.com/embed/pSI7sd_p4Yc",
        acess: "https://www.youtube.com/embed/pSI7sd_p4Yc",
        heldIn: "Produção Audiovisual para Crianças e Adolescentes - Optativa",
        partcipants: "Amanda Milena",
    },
    {
        id: 4,
        categoryId: [0],
        name: "O menino e o Supercão",
        description: "Ao fazer uso da imaginação, um menino e seu brinquedo favorito, um super cachorro de pelúcia, vivem grandes aventuras.",
        descriptionCard: "Ao fazer uso da imaginação, um menino e seu brinquedo favorito, um super cachorro de pelúcia, vivem grandes aventuras.",
        imgUrl: "../images/projects/4.jpg",
        demoUrl: "https://www.youtube.com/embed/Pgoip1x1kCg",
        acess: "https://www.youtube.com/embed/Pgoip1x1kCg",
        heldIn: "Produção Audiovisual para Crianças e Adolescentes - Optativa",
        partcipants: "Caio Orleans",
    },
    {
        id: 5,
        categoryId: [0],
        name: "Brincadeiras da minha infância",
        description: "O curta é um lapso de memória de coisas que me lembram minha infância, quase como se fosse um sonho de como era um dia da minha vida na época que era criança.",
        descriptionCard: "O curta é um lapso de memória de coisas que me lembram minha infância.",
        imgUrl: "../images/projects/5.jpg",
        demoUrl: "https://www.youtube.com/embed/ozvc2_In9Uk",
        acess: "https://www.youtube.com/embed/Pgoip1x1kCg",
        heldIn: "Produção Audiovisual para Crianças e Adolescentes - Optativa",
        partcipants: "Adrian Teixeira",
    },
    {
        id: 6,
        categoryId: [0],
        name: "Na Cesta",
        description: "Um grupo de crianças se reúne na rua para brincar com uma bola frente à casa de uma senhora. Durante a brincadeira, jogando a bola de uma para a outra, uma das crianças atinge o portão de ferro da casa vizinha, fazendo um grande barulho.",
        descriptionCard: "Um grupo de crianças se reúne na rua para brincar com uma bola frente à casa de uma senhora.",
        imgUrl: "../images/projects/6.jpg",
        demoUrl: "https://www.youtube.com/embed/mzbUmUTZero",
        acess: "https://www.youtube.com/embed/mzbUmUTZero",
        heldIn: "Produção Audiovisual para Crianças e Adolescentes - Optativa",
        partcipants: "Amanda Milena",
    },
    {
        id: 7,
        categoryId: [0],
        name: "Jogos de carta e Infância",
        description: "Sendo alguém que jogou diversos jogos de cartas nos últimos 16 conto um pouco sobre minha paixão pelo hobby, explorando os elementos que me fascinam neste.",
        descriptionCard: "Sendo alguém que jogou diversos jogos de cartas nos últimos 16 conto um pouco sobre minha paixão pelo hobby, explorando os elementos que me fascinam neste.",
        imgUrl: "../images/projects/7.jpg",
        demoUrl: "https://www.youtube.com/embed/4i8ao5-Jujo",
        acess: "https://www.youtube.com/embed/4i8ao5-Jujo",
        heldIn: "Produção Audiovisual para Crianças e Adolescentes - Optativa",
        partcipants: "Gabriel Marques",
    },
    {
        id: 8,
        categoryId: [0],
        name: "A nave espacial",
        description: "Duas meninas brincam em uma rede se revezando ao balançar, até que uma delas tem a ideia de se fechar totalmente dentro da rede, abrindo as portas da criatividade.",
        descriptionCard: "Duas meninas brincam em uma rede se revezando ao balançar, até que uma delas tem a ideia de se fechar totalmente dentro da rede, abrindo as portas da criatividade.",
        imgUrl: "../images/projects/8.jpg",
        demoUrl: "https://www.youtube.com/embed/rqnJl0Zf7Nk",
        acess: "https://www.youtube.com/embed/rqnJl0Zf7Nk",
        heldIn: "Produção Audiovisual para Crianças e Adolescentes - Optativa",
        partcipants: "Georgia Rebeka",
    },
    {
        id: 9,
        categoryId: [0],
        name: "Fundo de Quintal",
        description: "Guilherme está em completo tédio no quintal da avó. Sem saber do que brincar, ele começa a imaginar as possibilidades",
        descriptionCard: "Guilherme está em completo tédio no quintal da avó. Sem saber do que brincar, ele começa a imaginar as possibilidades",
        imgUrl: "../images/projects/9.jpg",
        demoUrl: "https://www.youtube.com/embed/MHrASwIngHM",
        acess: "https://www.youtube.com/embed/MHrASwIngHM",
        heldIn: "Produção Audiovisual para Crianças e Adolescentes - Optativa",
        partcipants: "Guilherme Sousa",
    },
    {
        id: 10,
        categoryId: [0],
        name: "Velha Infância",
        description: "Em um fim de tarde, o neto mais velho chega na casa de sua avó e se depara com uma cena, seu primo mais novo está sentado no sofá completamente hipnotizado pela tela do celular. Enquanto ele percebe as diferenças entre épocas, o rapaz mais velho se recorda dos momentos de fim de tarde na sua infância, onde aparecem diversos momentos vividos pelo rapaz anos atrás naquele mesmo horário.",
        descriptionCard: "Em um fim de tarde, o neto mais velho chega na casa de sua avó e se depara com uma cena, seu primo mais novo está sentado no sofá completamente hipnotizado pela tela do celular.",
        imgUrl: "../images/projects/10.jpg",
        demoUrl: "https://www.youtube.com/embed/KtfCZKeOyTw",
        acess: "https://www.youtube.com/embed/KtfCZKeOyTw",
        heldIn: "Produção Audiovisual para Crianças e Adolescentes - Optativa",
        partcipants: "Igor França",
    },
    {
        id: 11,
        categoryId: [0],
        name: "Desmemoriada",
        description: "Isis é do tipo de pessoa que não tem uma boa memória, tem dificuldade de lembrar do que já viveu, dos rostos, lugares e situações na ordem correta em que elas aconteceram. Mesmo assim, tenta reviver sua infância através das brincadeiras marcantes de quando era criança.",
        descriptionCard: "Isis é do tipo de pessoa que não tem uma boa memória, tem dificuldade de lembrar do que já viveu, dos rostos, lugares e situações na ordem correta em que elas aconteceram.",
        imgUrl: "../images/projects/11.jpg",
        demoUrl: "https://www.youtube.com/embed/xO44UPVUazY",
        acess: "https://www.youtube.com/embed/xO44UPVUazY",
        heldIn: "Produção Audiovisual para Crianças e Adolescentes - Optativa",
        partcipants: "Isis Lira",
    },
    {
        id: 12,
        categoryId: [0],
        name: "Aventuras da imaginação",
        description: "Uma menininha de sete anos tem uma imaginação enorme e vive diversas aventuras, sem sair do seu quarto. Dessa vez, ela decidiu pegar sua mochila e explorar uma floresta peculiar, até que...",
        descriptionCard: "Uma menininha de sete anos tem uma imaginação enorme e vive diversas aventuras, sem sair do seu quarto. Dessa vez, ela decidiu pegar sua mochila e explorar uma floresta peculiar, até que...",
        imgUrl: "../images/projects/12.jpg",
        demoUrl: "https://www.youtube.com/embed/XKJhYhVdWRQ",
        acess: "https://www.youtube.com/embed/XKJhYhVdWRQ",
        heldIn: "Produção Audiovisual para Crianças e Adolescentes - Optativa",
        partcipants: "Kiara Beatriz",
    },
    {
        id: 13,
        categoryId: [0],
        name: "Velha Infância",
        description: "Velha infância é sobre uma criança que é filha única e que brevemente consegue experimentar como é ter um irmão, mesmo que não seja de sangue.",
        descriptionCard: "Velha infância é sobre uma criança que é filha única e que brevemente consegue experimentar como é ter um irmão, mesmo que não seja de sangue.",
        imgUrl: "../images/projects/13.jpg",
        demoUrl: "https://www.youtube.com/embed/E7YmJw2QhVM",
        acess: "https://www.youtube.com/embed/E7YmJw2QhVM",
        heldIn: "Produção Audiovisual para Crianças e Adolescentes - Optativa",
        partcipants: "Larissa Rodrigues",
    },
    {
        id: 14,
        categoryId: [0],
        name: "O menino e o mapa",
        description: "O curta mostra uma criança, um menino que voltava da escola para sua casa em busca de se aventurar na leitura de um mapa-múndi, um atlas e assim cair em inúmeras aventuras.",
        descriptionCard: "O curta mostra uma criança, um menino que voltava da escola para sua casa em busca de se aventurar na leitura de um mapa-múndi, um atlas e assim cair em inúmeras aventuras.",
        imgUrl: "../images/projects/14.jpg",
        demoUrl: "https://www.youtube.com/embed/LqLPWAS9BF8",
        acess: "https://www.youtube.com/embed/LqLPWAS9BF8",
        heldIn: "Produção Audiovisual para Crianças e Adolescentes - Optativa",
        partcipants: "Pedro Lucas",
    },
    {
        id: 15,
        categoryId: [0],
        name: "Casa de vó",
        description: "Parece que casa de vó é um lugar mágico, vira oficina da imaginação. E assim, coisas que poderiam ir para o lixo se tornam brinquedos divertidos.  A mini Rachel viveu isso e transformou muitas coisas em brinquedos, pois casa de vó é isso.",
        descriptionCard: "Parece que casa de vó é um lugar mágico, vira oficina da imaginação. E assim, coisas que poderiam ir para o lixo se tornam brinquedos divertidos.",
        imgUrl: "../images/projects/15.jpg",
        demoUrl: "https://www.youtube.com/embed/tWT9h5dCtis",
        acess: "https://www.youtube.com/embed/tWT9h5dCtis",
        heldIn: "Produção Audiovisual para Crianças e Adolescentes - Optativa",
        partcipants: "Rachel Virginia",
    },
    {
        id: 16,
        categoryId: [0],
        name: "Vagalua",
        description: "Uma raposa solitária tenta fazer amizade com um vagalume e acaba em uma jornada que a leva até a lua.",
        descriptionCard: "Uma raposa solitária tenta fazer amizade com um vagalume e acaba em uma jornada que a leva até a lua.",
        imgUrl: "../images/projects/16.jpg",
        demoUrl: "https://www.youtube.com/embed/adw275YnR4c",
        acess: "https://www.youtube.com/embed/adw275YnR4c",
        heldIn: "Produção Audiovisual para Crianças e Adolescentes - Optativa",
        partcipants: "Raimundo Thales",
    },
    {
        id: 17,
        categoryId: [0],
        name: "Florescendo",
        description: "Iara é uma menina de 8 anos que ama brincar nos arredores de sua casa, na Vila. Junto com seus vizinhos Cice, Jovi e Chico, o 'esconde-esconde' é sempre a escolha número 1 para a diversão da noite. Porém, as crianças estão crescendo e não conseguem mais se esconder tão facilmente quanto antes. Felizmente, isso não impede a diversão quando o quarteto está reunido.",
        descriptionCard: "Iara é uma menina de 8 anos que ama brincar nos arredores de sua casa, na Vila. Junto com seus vizinhos Cice, Jovi e Chico, o 'esconde-esconde' é sempre a escolha número 1 para a diversão da noite.",
        imgUrl: "../images/projects/17.jpg",
        demoUrl: "https://www.youtube.com/embed/K31QS5LZJ8M",
        acess: "https://www.youtube.com/embed/K31QS5LZJ8M",
        heldIn: "Produção Audiovisual para Crianças e Adolescentes - Optativa",
        partcipants: "Vitória Cristina",
    },
    {
        id: 18,
        categoryId: [0],
        name: "Os ovos da galinha Juju",
        description: "Maria é uma menininha muito feliz, e que passa as férias na casa da avó, lá ela e seu priminho jônatas se divertem e aprontam muitas aventuras na natureza, nesse episódio eles vão em busca do ninho perdido de ovos da galinha da sua avó.",
        descriptionCard: "Maria e seu priminho jônatas se divertem e aprontam muitas aventuras na natureza, nesse episódio eles vão em busca do ninho perdido de ovos da galinha da sua avó",
        imgUrl: "../images/projects/18.jpg",
        demoUrl: "https://www.youtube.com/embed/0DYKR9QMKbI",
        acess: "https://www.youtube.com/embed/0DYKR9QMKbI",
        heldIn: "Produção Audiovisual para Crianças e Adolescentes - Optativa",
        partcipants: "Vitória Régia",
    },
    {
        id: 19,
        categoryId: [0],
        name: "Revista Catorze Trinta",
        description: "Catorze Trinta é uma revista digital semestral da disciplina Redação para Mídias Digitais, do curso Sistemas e Mídias Digitais da Universidade Federal do Ceará. O nome da publicação é uma referência ao número do bloco didático do curso no Campus do Pici. A edição apresentada é a do semestre 2022.2, que teve como tema emoções e saúde mental.",
        descriptionCard: "Revista Catorze Trinta, produção de Redação para Mídias Digitais, que teve como tema emoções e saúde mental em 2022.2",
        imgUrl: "../images/projects/19.png",
        demoUrl: "../images/projects/demo/19.png",
        acess: "https://medium.com/catorze-trinta-ed-6",
        heldIn: "Redação para Mídias Digitais - Optativa (Requisitos: NARRATIVAS MULTIMÍDIA – SEMIÓTICA APLICADA)",
        partcipants: "Alunos da disciplina de Redação para Mídias Digitais.",
    },
    {
        id: 20,
        categoryId: [1, 2],
        name: "Caxangá",
        description: "Jogo de cartas para desktop com a temática do folclore brasileiro.",
        descriptionCard: "Jogo de cartas para desktop com a temática do folclore brasileiro.",
        imgUrl: "../images/projects/20.png",
        demoUrl: "https://www.youtube.com/embed/TL4yK3fmAtw",
        acess: "https://www.behance.net/gallery/133575603/Caxanga-Estudo-de-caso-UIUX",
        heldIn: "Projeto Integrado II - 6° Semestre",
        partcipants: "Alexandre Machado, João Victor de Alencar, Leonardo Sambonet, Tiego Campos, Ana Luiza Silveira",
    },
    {
        id: 21,
        categoryId: [1],
        name: "Protótipo Solar",
        description: "Proposta de re-design do app do Solar com melhor usabilidade e design mais agradável,  tentando seguir a ideia de um MLP.",
        descriptionCard: "Proposta de re-design do app do Solar com melhor usabilidade e design mais agradável,  tentando seguir a ideia de um MLP.",
        imgUrl: "../images/projects/21.png",
        demoUrl: "../images/projects/21.png",
        acess: "https://www.figma.com/proto/GmKviFlW9AYp9aGphRBEb3/DAM---Prot%C3%B3tipo-Solar?type=design&node-id=38-4100&t=Wup9c4tYqRDCGciI-1&scaling=scale-down&page-id=6%3A46&starting-point-node-id=38%3A146&mode=design",
        heldIn: "Direção de Arte Multimídia - 7° Semestre",
        partcipants: "Ulisses Silva de Sousa, Antonio Caio Vieira de Souza, Raquel Lima de Almeida, Rebeca Praciano Haddad",
    },
    {
        id: 22,
        categoryId: [2,3],
        name: "SM O quê?",
        description: "Um jogo de tabuleiro online com tema do Mario para introduzir e ensinar aos alunos do primeiro semestre sobre o funcionamento da grade curricular do SMD e das trilhas que compõem o curso, contendo ainda um teste de personalidade que indica qual trilha combina mais com você!",
        descriptionCard: "Um jogo de tabuleiro online com tema do Mario para introduzir e ensinar aos alunos do primeiro semestre sobre o funcionamento da grade curricular do SMD e das trilhas que compõem o curso.",
        imgUrl: "../images/projects/22.png",
        demoUrl: "../images/projects/demo/22.png",
        acess: "https://playingcards.io/urs7aw",
        heldIn: "Design de jogos educacionais - Optativa (Realizado no 1° Semestre)",
        partcipants: "Maria Clara de Oliveira Alexandre",
    },
]

export { projects };