const graduates = [
    {
        id: 0,
        name: "Jonas Forte",
        imgUrl: "../images/graduates/0.jpeg",
        location: "Brescia, Itália",
        positionInMap: ['40vw', '13vw', '98.5vw', '15vh'],
        graduateYear: "2017",
        job: "UI Designer - Luxottica",
        contact: "https://linkedin.com/in/jonasforte",
        bio: "Sou apaixonado por interação homem-máquina, design de interfaces gráficas e inteligência artificial. Em 2018, mudei-me para a Itália para fazer meu mestrado de engenharia em Tecnologias de Informação e Multimídia. Atualmente, trabalho na marca Sunglass Hut, em projetos de roadmap, campanhas de marcas licenciadas e internas.",
        aboutSMD: "Meu percurso acadêmico foi fundamental para meu crescimento pessoal e profissional, proporcionando-me a oportunidade de descobrir novas paixões e vivenciar experiências inesperadas.",
    },
    {
        id: 1,
        name: "Taynara Menezes",
        imgUrl: "../images/graduates/1.jpeg",
        location: "Osasco, Brasil",
        positionInMap: ['24vw', '30vw','62vw', '34vh'],
        graduateYear: "2018.1",
        job: "Senior Product Designer no iFood",
        contact: "https://www.linkedin.com/in/taynara-menezes/",
        bio: "Eu sou Taynara Menezes, uma Product Designer no iFood e artista nas horas vagas, natural de Fortaleza, Ceará. Iniciei minha carreira no desenvolvimento de software, mas encontrei minha verdadeira paixão no design de produtos digitais durante o curso de Sistemas e Mídias Digitais na UFC. Atuei como diretora de arte em agências locais antes de alcançar minha posição atual como designer de experiência no iFood. Com especialização em Design de Interação, meu objetivo é facilitar a vida das pessoas e trazer uma perspectiva centrada no usuário para os negócios. Além disso, minha paixão pela arte me permite explorar diferentes formas de expressão visual. Estou dedicada a criar experiências significativas e funcionais, deixando um impacto positivo no mundo através do design e da arte",
        aboutSMD: "Quando entrei no curso de Sistemas e Mídias Digitais, que foi minha primeira e  segunda opção no Sisu (eu realmente queria esse curso), percebi que era exatamente o que eu queria fazer. Eu sempre fui uma pessoa interessada em várias coisas, e esse curso abrangente me permitiu explorar diferentes áreas de conhecimento. Isso me ajudou a me tornar uma profissional que sabe se comunicar bem com pessoas de diferentes áreas e contribuir em diversos assuntos. Foi nesse curso que descobri minha verdadeira paixão pelo Design, que vejo como uma ponte entre a tecnologia e as necessidades das pessoas. Acredito que o curso de Sistemas e Mídias Digitais me levou a um caminho criativo e amplo, onde tenho a oportunidade de aportar para diferentes áreas de conhecimento e conduzir projetos incríveis ao longo da minha carreira.",
    },
    {
        id: 2,
        name: "Espedito Roza",
        imgUrl: "../images/graduates/2.jpeg",
        location: "Fortaleza, Brasil",
        positionInMap: ['28vw', '23vw', '68vw', '28vh'],
        graduateYear: "2021",
        job: "UX Tribe Lead na Intmed Software",
        contact: "https://www.linkedin.com/in/espeditoroza/ ",
        bio: "Sou Designer de Produto e nos últimos 5 anos ajudei a criar produtos e experiências para os setores público e privado. Sou formado em SMD pela UFC e tenho pós-graduação em UX Design and Beyond pela PUCRS. Já trabalhei nos nichos de educação, finanças, segurança pública, comércio, direitos humanos e saúde.\n\nAlém do SMD, na época de faculdade, fiz parte de projetos de empreendedorismo social e fui Diretor de Projetos da Container Digital Júnior - Empresa Júnior do SMD.\n\nHoje, além de trabalhar como UX Tribe Lead na Intmed Software, sou mentor de um projeto voluntário focado em fornecer educação em design para pessoas transgêneros, travestis e não-binárias. Além disso, faço parte de uma startup social que facilita o processo de retificação de nome e/ou gênero de pessoas trans e travestis.",
        aboutSMD: "O que me atraiu no SMD foi a grade curricular diversa, o que me manteve lá foi a dinamicidade do aprendizado. Muito além da teoria, sempre pude colocar em prática o que aprendia nas disciplinas.\n\nAtuei em competições de design, participei de eventos e hackathons e lidei com clientes reais - tanto em disciplinas, quanto na CoDi Júnior, a empresa júnior do curso. E essa gama de oportunidades que a UFC e o SMD me proporcionaram, me ajudaram a escolher a trilha que hoje sigo como profissão e onde utilizo aprendizados da época da faculdade dentro dos projetos que atuo.\n\nAs disciplinas e os professores do curso forneceram bastante conhecimento e experiência, não se limitando apenas a academia, mas expandindo para o mercado de trabalho. Hoje posso dizer que o SMD impactou a minha vida através do aprendizado em Design - e outras áreas correlacionadas -, assim como nas minhas habilidades de resolução de problemas, pesquisa, visão de mercado, gestão etc.",
    },
    {
        id: 3,
        name: "Pedro Ítalo da Costa Pinto",
        imgUrl: "../images/graduates/3.jpg",
        location: "Lisboa, Portugal",
        positionInMap: ['35vw', '13vw','87vw', '15vh'],
        graduateYear: "2017",
        job: "Senior IT Auditor na Volkswagen Group Services",
        contact: "https://www.linkedin.com/mwlite/in/pedro-italo-da-costa-pinto-259b39b8",
        bio: "Após concluir o SMD no final de 2017, trabalhei na KPMG Brasil por 4 anos e 8 meses na área de auditoria de TI, ingressando como trainee e saindo como supervisor. Em abril de 2023 fui contratado pela Volkswagen Group Services para ingressar no Hub de Auditoria de TI em Lisboa, para realização de auditorias nas empresas do grupo Volkswagen.",
        aboutSMD: "Apesar de não trabalhar numa área 'padrão' do itinerário formativo do curso, o SMD me deu a base técnica de sistemas que me ajudou bastante no meu trabalho, principalmente no início. Além disso, a mentalidade de solução de problemas e trabalho em equipe do curso me auxiliam diariamente na execução das minhas tarefas na empresa.",
    },
    {
        id: 4,
        name: "Rafaelly Freitas",
        imgUrl: "../images/graduates/4.jpeg",
        location: "Santa Catarina, Brasil",
        positionInMap: ['22vw', '33vw', '55vw', '37vh'],
        graduateYear: "2021",
        job: "Product Designer - Asaas",
        contact: "https://www.linkedin.com/in/rafaelly-freitas/",
        bio: "Sou uma sonhadora que acredita que o brilho no olhar nos move, que nós podemos tudo que desejarmos e que muito cedo aprendeu que desistir não é uma opção. Iniciei minha carreira como desenvolvedora Web Full Stack, atuando por quase 4 anos dentro do ecossistema de Startups. Depois disso, migrei para o área do Design. Onde já atuei como UX/UI Designer e Product Designer.\n\nSomado a isso, outras oportunidades surgiram em paralelo na minha jornada através da universidade. No meio acadêmico, consegui ter experiências com iniciação à docência, escrita científica e empreendedorismo. Gostaria de destacar que conhecer o empreendedorismo através do Movimento Empresa Júnior (MEJ), me possibilitou atuar como gerente de projetos e ser liderança estratégica de um time incrível de 20 pessoas. Essa experiência me fez aprender muito sobre liderança, traçar, analisar e bater metas, além de muito trabalho em equipe.",
        aboutSMD: "O SMD foi uma grande escola na minha vida, e não só tecnicamente. Pelos corredores do bloco fiz amigos, amadureci, conheci professores incríveis e me redescobri profissionalmente. A universidade, se bem aproveitada, pode ser um laboratório para experimentar, errar e aprender. Dito isso, graças ao SMD, consegui me desenvolver de forma técnica e comportamental. Hoje sou uma profissional multidisciplinar que consegue dialogar bem com toda a equipe de tecnologia, e que principalmente, que consegue trabalhar bem em equipe.",
    },
    {
        id: 5,
        name: "Joelma Peixoto",
        imgUrl: "../images/graduates/5.jpg",
        location: "Ontario, Canada",
        positionInMap: ['15vw', '10vw', '35vw', '15vh'],
        graduateYear: " 2014.2",
        job: "Último ano de PhD na Ontario Tech University",
        contact: "https://www.linkedin.com/in/joelma-jlmpxt/",
        bio: "Joelma Peixoto é bacharel em Sistemas e Mídias Digitais e mestre em Ciência da Computação pela Universidade Federal do Ceará. Atualmente, ela está cursando seu Ph.D. em Engenharia Elétrica e da Computação na Ontario Tech University. Tem experiência em aprendizado de máquina, sistemas multimídia, computação ubíqua e robótica.",
        aboutSMD: "O curso me possibilitou aprender e testar inúmeras tecnologias, assim como me permitiu colocar minhas ideias em prática por meio dos projetos das disciplinas.",
    },
];

export { graduates };