const projects = [
    {
        id: 0,
        categoryId: 0,
        name: "Ariel",
        description: "Controle suas aplicações de testosterona. Acompanhe suas consultas médicas. Informe-se através de artigos e muito mais.",
        descriptionCard: "Controle suas aplicações de testosterona. Acompanhe suas consultas médicas. Informe-se através de artigos e muito mais.",
        imgUrl: "../source/project.png",
        videoUrl: "https://www.youtube.com/embed/t-hK0KsicPQ",
        heldIn: "Projeto II",
        partcipants: "Amanda Milena",
    },
    {
        id: 1,
        categoryId: 1,
        name: "Imaginarium - Uma Leitura Brincante",
        description: "Amanda é uma criança comum. Ela tem amigos, diverte-se com eles, mas em certos momentos se encontra solitária e fica triste. Por muito tempo, Amanda acreditou que não havia graça em brincar sozinha. Imagine a surpresa dela ao descobrir a sua brincadeira preferida na vida, incomum e maravilhosa…",
        descriptionCard: "Amanda é uma criança comum. Ela tem amigos, diverte-se com eles, mas em certos momentos se encontra solitária e fica triste.",
        imgUrl: "../source/project.png",
        videoUrl: "https://www.youtube.com/embed/pSI7sd_p4Yc",
        heldIn: "Produção Audiovisual para Crianças e Adolescentes, em 2022.2",
        partcipants: "Amanda Milena",
    },
    {
        id: 2,
        categoryId: 1,
        name: "Imaginarium - Uma Leitura Brincante",
        description: "Amanda é uma criança comum. Ela tem amigos, diverte-se com eles, mas em certos momentos se encontra solitária e fica triste. Por muito tempo, Amanda acreditou que não havia graça em brincar sozinha. Imagine a surpresa dela ao descobrir a sua brincadeira preferida na vida, incomum e maravilhosa…",
        descriptionCard: "Amanda é uma criança comum. Ela tem amigos, diverte-se com eles, mas em certos momentos se encontra solitária e fica triste.",
        imgUrl: "../source/project.png",
        videoUrl: "https:/www.youtube.com/embed/pSI7sd_p4Yc",
        heldIn: "Produção Audiovisual para Crianças e Adolescentes, em 2022.2",
        partcipants: "Amanda Milena",
    },
    {
        id: 3,
        categoryId: 2,
        name: "Imaginarium - Uma Leitura Brincante",
        description: "Amanda é uma criança comum. Ela tem amigos, diverte-se com eles, mas em certos momentos se encontra solitária e fica triste. Por muito tempo, Amanda acreditou que não havia graça em brincar sozinha. Imagine a surpresa dela ao descobrir a sua brincadeira preferida na vida, incomum e maravilhosa…",
        descriptionCard: "Amanda é uma criança comum. Ela tem amigos, diverte-se com eles, mas em certos momentos se encontra solitária e fica triste.",
        imgUrl: "../source/project.png",
        videoUrl: "https:/www.youtube.com/embed/pSI7sd_p4Yc",
        heldIn: "Produção Audiovisual para Crianças e Adolescentes, em 2022.2",
        partcipants: "Amanda Milena",
    },
    {
        id: 4,
        categoryId: 2,
        name: "Imaginarium - Uma Leitura Brincante",
        description: "Amanda é uma criança comum. Ela tem amigos, diverte-se com eles, mas em certos momentos se encontra solitária e fica triste. Por muito tempo, Amanda acreditou que não havia graça em brincar sozinha. Imagine a surpresa dela ao descobrir a sua brincadeira preferida na vida, incomum e maravilhosa…",
        descriptionCard: "Amanda é uma criança comum. Ela tem amigos, diverte-se com eles, mas em certos momentos se encontra solitária e fica triste.",
        imgUrl: "../source/project.png",
        videoUrl: "https:/www.youtube.com/embed/pSI7sd_p4Yc",
        heldIn: "Produção Audiovisual para Crianças e Adolescentes, em 2022.2",
        partcipants: "Amanda Milena",
    },
    {
        id: 5,
        categoryId: 3,
        name: "O menino e o Supercão",
        description: "Ao fazer uso da imaginação, um menino e seu brinquedo favorito, um super cachorro de pelúcia, vivem grandes aventuras.",
        descriptionCard: "Ao fazer uso da imaginação, um menino e seu brinquedo favorito, um super cachorro de pelúcia, vivem grandes aventuras.",
        imgUrl: "../source/project.png",
        videoUrl: "https://www.youtube.com/embed/Pgoip1x1kCg",
        heldIn: "Produção Audiovisual para Crianças e Adolescentes, em 2022.2",
        partcipants: "Caio Orleans",
    },
    {
        id: 6,
        categoryId: 3,
        name: "Imaginarium - Uma Leitura Brincante",
        description: "Amanda é uma criança comum. Ela tem amigos, diverte-se com eles, mas em certos momentos se encontra solitária e fica triste. Por muito tempo, Amanda acreditou que não havia graça em brincar sozinha. Imagine a surpresa dela ao descobrir a sua brincadeira preferida na vida, incomum e maravilhosa…",
        descriptionCard: "Amanda é uma criança comum. Ela tem amigos, diverte-se com eles, mas em certos momentos se encontra solitária e fica triste.",
        imgUrl: "../images/projects/imaginarium.png",
        videoUrl: "https://www.youtube.com/embed/pSI7sd_p4Yc",
        heldIn: "Produção Audiovisual para Crianças e Adolescentes, em 2022.2",
        partcipants: "Amanda Milena",
    },
    {
        id: 7,
        categoryId: 3,
        name: "Brincadeiras da minha infância",
        description: "O curta é um lapso de memória de coisas que me lembram minha infância, quase como se fosse um sonho de como era um dia da minha vida ná época que era criança.",
        descriptionCard: "O curta é um lapso de memória de coisas que me lembram minha infância.",
        imgUrl: "../source/project.png",
        videoUrl: "https://www.youtube.com/embed/ozvc2_In9Uk",
        heldIn: "Produção Audiovisual para Crianças e Adolescentes, em 2022.2",
        partcipants: "Adrian Teixeira",
    },
    {
        id: 8,
        categoryId: 3,
        name: "Na Cesta",
        description: "Um grupo de crianças se reúne na rua para brincar com uma bola frente à casa de uma senhora. Durante a brincadeira, jogando a bola de uma para a outra, uma das crianças atinge o portão de ferro da casa vizinha, fazendo um grande barulho.",
        descriptionCard: "Um grupo de crianças se reúne na rua para brincar com uma bola frente à casa de uma senhora.",
        imgUrl: "../source/project.png",
        videoUrl: "https://www.youtube.com/embed/mzbUmUTZero",
        heldIn: "Produção Audiovisual para Crianças e Adolescentes, em 2022.2",
        partcipants: "Amanda Milena",
    }
]

export { projects };