const graduates = [
    {
        id: 0,
        name: "Jonas Forte",
        imgUrl: "../images/graduates/0.jpeg",
        location: "Brescia, Itália",
        positionInMap: ['40vw', '20vw'],
        graduateYear: "2017",
        job: "UI Designer - Luxottica",
        contact: "https://linkedin.com/in/jonasforte",
        bio: "Sou apaixonado por interação homem-máquina, design de interfaces gráficas e inteligência artificial. Em 2018, mudei-me para a Itália para fazer meu mestrado de engenharia em Tecnologias de Informação e Multimídia. Atualmente, trabalho na marca Sunglass Hut, em projetos de roadmap, campanhas de marcas licenciadas e internas.",
        aboutSMD: "Meu percurso acadêmico foi fundamental para meu crescimento pessoal e profissional, proporcionando-me a oportunidade de descobrir novas paixões e vivenciar experiências inesperadas.",
    },
    {
        id: 1,
        name: "Taynara Menezes",
        imgUrl: "../images/graduates/1.jpeg",
        location: "Fortaleza, Ceará",
        positionInMap: ['50vw', '40vw'],
        graduateYear: "2018.1",
        job: "Senior Product Designer no iFood",
        contact: "https://www.linkedin.com/in/taynara-menezes/",
        bio: "Eu sou Taynara Menezes, uma Product Designer no iFood e artista nas horas vagas, natural de Fortaleza, Ceará. Iniciei minha carreira no desenvolvimento de software, mas encontrei minha verdadeira paixão no design de produtos digitais durante o curso de Sistemas e Mídias Digitais na UFC. Atuei como diretora de arte em agências locais antes de alcançar minha posição atual como designer de experiência no iFood. Com especialização em Design de Interação, meu objetivo é facilitar a vida das pessoas e trazer uma perspectiva centrada no usuário para os negócios. Além disso, minha paixão pela arte me permite explorar diferentes formas de expressão visual. Estou dedicada a criar experiências significativas e funcionais, deixando um impacto positivo no mundo através do design e da arte",
        aboutSMD: "Quando entrei no curso de Sistemas e Mídias Digitais, que foi minha primeira e  segunda opção no Sisu (eu realmente queria esse curso), percebi que era exatamente o que eu queria fazer. Eu sempre fui uma pessoa interessada em várias coisas, e esse curso abrangente me permitiu explorar diferentes áreas de conhecimento. Isso me ajudou a me tornar uma profissional que sabe se comunicar bem com pessoas de diferentes áreas e contribuir em diversos assuntos. Foi nesse curso que descobri minha verdadeira paixão pelo Design, que vejo como uma ponte entre a tecnologia e as necessidades das pessoas. Acredito que o curso de Sistemas e Mídias Digitais me levou a um caminho criativo e amplo, onde tenho a oportunidade de aportar para diferentes áreas de conhecimento e conduzir projetos incríveis ao longo da minha carreira.",
    },
    // {
    //     id: 2,
    //     name: "Jonas Forte",
    //     imgUrl: "../images/0.jpeg",
    //     location: "Brescia, Itália",
    //     positionInMap: ['35vw', '45vw'],
    //     graduateYear: "2017",
    //     job: "UI Designer - Luxottica",
    //     contact: "https://linkedin.com/in/jonasforte",
    //     bio: "Sou apaixonado por interação homem-máquina, design de interfaces gráficas e inteligência artificial. Em 2018, mudei-me para a Itália para fazer meu mestrado de engenharia em Tecnologias de Informação e Multimídia. Atualmente, trabalho na marca Sunglass Hut, em projetos de roadmap, campanhas de marcas licenciadas e internas.",
    //     aboutSMD: "Meu percurso acadêmico foi fundamental para meu crescimento pessoal e profissional, proporcionando-me a oportunidade de descobrir novas paixões e vivenciar experiências inesperadas.",
    // },
];

export { graduates };