const projects = [
    {
        id: 0,
        categoryId: [1, 2, 3],
        name: "Gestus",
        description: "Gestus é um recurso educativo digital composto por minigames que ensinam termos em LIBRAS para crianças de 7 a 10 anos. O  jogo dispõe de uma narrativa onde o personagem principal, Jonas, ajuda a ambientar a história dentro de uma cidade, onde cada local — casa, sorveteria, supermercado, fliperama e escola — comporta um aprendizado. \nEm Gestus se aborda o básico de LIBRAS por meio de módulos. Essa separação em módulos proporciona uma maior flexibilidade no momento da aula, pois permite que o professor escolha a quantidade de módulos por aula e aumenta as possibilidades de uso da aplicação. \nO  jogo Gestus tem por finalidade aproximar o contato de crianças, entre 7 a 10 anos de idade, com o ensino de LIBRAS, de modo a tornar natural esse processo de aprendizado através de jogos, bem como auxiliar no processo de adaptação de crianças ouvintes com crianças surdas em um mesmo espaço escolar.",
        descriptionCard: "Gestus é um recurso educativo digital composto por minigames que ensinam termos em LIBRAS para crianças de 7 a 10 anos.",
        imgUrl: "../images/projects/Gestus.png",
        demoUrl: "https://www.youtube.com/embed/PcrJng0BVeo",
        acess: "https://gestusjogo.github.io/",
        heldIn: "Projeto Integrado I - 3º semestre",
        partcipants: "Espedito Roza, José Monteiro, Rafaelly Freitas, Sarah Isabelle, Vinícius Dellvale",
    },
    {
        id: 1,
        categoryId: [1, 3],
        name: "Ariel",
        description: "O Projeto Ariel é uma plataforma que auxilia homens trans em todas as etapas da hormonoterapia. Ele oferece recursos personalizados para o controle das doses de testosterona, o acompanhamento de parâmetros como secreção vaginal, alterações de humor e mudanças corporais. Os usuários também podem registrar as mudanças físicas por meio de fotos, acessar artigos sobre saúde, humor e sociedade, adicionar eventos ao calendário para consultas e exames, além de acompanhar os níveis de testosterona para uma transição através de hormonoterapia saudável e bem-sucedida. O objetivo principal do Projeto Ariel é fornecer um suporte abrangente e personalizado aos homens trans durante todo o processo de hormonoterapia, auxiliando-os a ter uma transição segura, saudável e satisfatória. O projeto busca empoderar os usuários, fornecendo ferramentas e recursos que os capacitam a tomar decisões informadas, monitorar seu progresso, gerenciar sua saúde física e emocional, e se manterem atualizados com informações relevantes e de qualidade.\nAo oferecer uma plataforma que integra diversos recursos, desde o acompanhamento das doses de testosterona até o registro de mudanças físicas, leitura de artigos, calendário personalizado e monitoramento dos níveis hormonais, o Ariel visa simplificar e centralizar todas as informações e tarefas relacionadas à transição hormonal. Dessa forma, o projeto busca facilitar o processo para os homens trans, fornecendo uma ferramenta prática, confiável e acessível, que os acompanha em cada etapa de sua jornada de transição.",
        descriptionCard: "O Projeto Ariel é uma plataforma que auxilia homens trans em todas as etapas da hormonoterapia.",
        imgUrl: "../images/projects/Ariel.png",
        demoUrl: "https://www.youtube.com/embed/t-hK0KsicPQ",
        acess: "https://repositorio.ufc.br/handle/riufc/68044",
        heldIn: "Projeto Integrado II - 6º semestre",
        partcipants: "Versão menor do projeto: Espedito Roza, Matheus Felix, Rafinha Freitas, Sarah Isabelle:",
    },
    {
        id: 2,
        categoryId: [1, 2, 3],
        name: "The Gatsby’s Party",
        description: `O Projeto The Gatsby's Party é um jogo digital para desktop criado com o objetivo de testar os alunos em relação ao livro "The Great Gatsby" de Scott Fitzgerald. \nO jogo oferece uma abordagem interativa e envolvente para incentivar o aprendizado do livro, combinando elementos de quiz, escape room e exploração de objetos. O jogo começa com um quiz sobre o personagem escolhido pelo usuário. Para avançar no jogo, o jogador precisa acertar pelo menos 3 das 5 perguntas apresentadas. Isso garante que o jogador tenha um conhecimento básico sobre o livro e os personagens principais. Uma vez que o usuário tenha passado no quiz inicial, ele entra na festa de Gatsby. O jogo se desenrola em estilo escape room, onde o jogador precisa encontrar objetos, resolver enigmas e desafios para progredir e alcançar o objetivo final. Durante essa jornada, o jogador é exposto a informações sobre o livro, como curiosidades, trechos destacados e análises literárias. Essas informações complementares ajudam no aprendizado do livro de forma divertida e imersiva. \nO Projeto The Gatsby's Party busca não apenas testar os conhecimentos dos alunos, mas também promover o envolvimento e o interesse pela obra literária. Ao combinar elementos de jogo com aprendizado, o projeto oferece uma experiência interativa que estimula a curiosidade e a exploração do universo de "The Great Gatsby", tornando o processo de estudo mais envolvente e prazeroso.`,
        descriptionCard: `O Projeto The Gatsby's Party é um jogo digital para desktop criado com o objetivo de testar os alunos em relação ao livro "The Great Gatsby" de Scott Fitzgerald.`,
        imgUrl: "../images/projects/Gatsby.png",
        demoUrl: "../images/projects/GatsbyDemo.png",
        acess: "https://thegatsbyparty.github.io/index.html ",
        heldIn: "Avaliação Interdisciplinar - 2º semestre",
        partcipants: "Arlindo Júnior, Davi Calisto, Espedito Roza, Sarah Isabelle, Vinícius Dellvale",
    },
    {
        id: 3,
        categoryId: [0],
        name: "Imaginarium - Uma Leitura Brincante",
        description: "Amanda é uma criança comum. Ela tem amigos, diverte-se com eles, mas em certos momentos se encontra solitária e fica triste. Por muito tempo, Amanda acreditou que não havia graça em brincar sozinha. Imagine a surpresa dela ao descobrir a sua brincadeira preferida na vida, incomum e maravilhosa…",
        descriptionCard: "Amanda é uma criança comum. Ela tem amigos, diverte-se com eles, mas em certos momentos se encontra solitária e fica triste.",
        imgUrl: "../images/projects/Imaginarium.png",
        demoUrl: "https://www.youtube.com/embed/pSI7sd_p4Yc",
        heldIn: "Produção Audiovisual para Crianças e Adolescentes, em 2022.2",
        partcipants: "Amanda Milena",
    },
    {
        id: 4,
        categoryId: [0],
        name: "O menino e o Supercão",
        description: "Ao fazer uso da imaginação, um menino e seu brinquedo favorito, um super cachorro de pelúcia, vivem grandes aventuras.",
        descriptionCard: "Ao fazer uso da imaginação, um menino e seu brinquedo favorito, um super cachorro de pelúcia, vivem grandes aventuras.",
        imgUrl: "../source/project.png",
        demoUrl: "https://www.youtube.com/embed/Pgoip1x1kCg",
        heldIn: "Produção Audiovisual para Crianças e Adolescentes, em 2022.2",
        partcipants: "Caio Orleans",
    },
    {
        id: 5,
        categoryId: [0],
        name: "Brincadeiras da minha infância",
        description: "O curta é um lapso de memória de coisas que me lembram minha infância, quase como se fosse um sonho de como era um dia da minha vida ná época que era criança.",
        descriptionCard: "O curta é um lapso de memória de coisas que me lembram minha infância.",
        imgUrl: "../source/project.png",
        demoUrl: "https://www.youtube.com/embed/ozvc2_In9Uk",
        heldIn: "Produção Audiovisual para Crianças e Adolescentes, em 2022.2",
        partcipants: "Adrian Teixeira",
    },
    {
        id: 6,
        categoryId: [0],
        name: "Na Cesta",
        description: "Um grupo de crianças se reúne na rua para brincar com uma bola frente à casa de uma senhora. Durante a brincadeira, jogando a bola de uma para a outra, uma das crianças atinge o portão de ferro da casa vizinha, fazendo um grande barulho.",
        descriptionCard: "Um grupo de crianças se reúne na rua para brincar com uma bola frente à casa de uma senhora.",
        imgUrl: "../source/project.png",
        demoUrl: "https://www.youtube.com/embed/mzbUmUTZero",
        heldIn: "Produção Audiovisual para Crianças e Adolescentes, em 2022.2",
        partcipants: "Amanda Milena",
    }
]

export { projects };